FROM python:3.10-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt . 
RUN pip install -r requirements.txt

# Copiar o código para o diretório /app no contêiner
COPY . /app

# Comando de execução
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
